### ISSUE TITLE
Avoid adding global styles

### ISSUE THREAD

**Issue by KELiON** [rafa-acioly/cerebro-convertcolor#4]
Hey!

Thanks for this great plugin! One thing that would be nice to fix is overriding global styles. You can found details [in this issue](https://github.com/KELiON/cerebro/issues/269#issuecomment-292558202).

**Comment by rafa-acioly** [comment]
Hi @KELiON, sorry about that!
Already fix it removing `bulma css`, you can check the update on this commit 9c8a830dbfc034318540cc69f97e634df877b697

**Comment by KELiON** [comment]
Fixed! Thanks!
