### ISSUE TITLE
Few thoughts about plugin improvement

### ISSUE THREAD

**Issue by KELiON** [rafa-acioly/cerebro-convertcolor#5]
Hey, @rafa-acioly! 

Your plugin looks good and for a long time I had this plugin in my list of ideas:) 

So, now I have few thoughts about how to improve this plugin, that I want to discuss:

1) Add support for rgba colors, like `rgba(255, 255, 100, 0.5)` or `rgba(255, 255, 100, .5)`
2) Remove `convertColor` keyword. I think it makes sense to use this plugin just by regexp, so plugin could be used for all inputs that match:
1) `#`+6 chars it is color, like `#cceebb`
2) `rgb(...,...,...)`

More ideas could be taken from google preview: 
![image](https://cloud.githubusercontent.com/assets/594298/24815609/0f7d6074-1bd6-11e7-9af3-eb5365b452a2.png)

So, they support some more formats (I'm not sure they are useful, but could be for designers) and also they have colorpicker in their preview. 

What do you think?

**Comment by rafa-acioly** [comment]
Hi @KELiON
I really like the idea of implementing "out of the plugin" without the keyword "convertColor".

I will start working on it as fast as I can and if you can send some pull requests I will be very grateful.
My "node knowledge" is not so deep so I will need help structuring the files, could you help me?

**Comment by rafa-acioly** [comment]
@KELiON I'm having trouble displaying the results in the same way that the stackoverflow plugin does, could you give me a hand?

**Comment by KELiON** [comment]
Hey, @rafa-acioly! Sure, what is your problem? I've just tried your new branch, did small change to use [create-cerebro-plugin](https://github.com/KELiON/create-cerebro-plugin) scripts in #6 and it works like this: 

![image](https://user-images.githubusercontent.com/594298/28964931-3b9b9bda-790f-11e7-9b6b-9aa581c5a019.png)

**Comment by rafa-acioly** [comment]
@KELiON I managed to solve by grabbing code snippets from the "emoji" plugin!
But the design is awful, do you have any idea what I can do?

**Comment by KELiON** [comment]
What do you think about this option? It is simple, keyboard-accessible (arrows, enter to copy) and consistent with other plugins (like google):


![screen shot 2017-08-04 at 17 28 18](https://user-images.githubusercontent.com/594298/28975456-5a131d1a-793a-11e7-84c0-c9a86f06c9f6.png)


You can check it #7

**Comment by rafa-acioly** [comment]
@KELiON just awesome, thank you!

**Comment by KELiON** [comment]
Thanks for great job @rafa-acioly! I'm closing this issue and I've added two small ones #10 #9 instead :)
